import Head from 'next/head'
import Image from 'next/image'
import Stack from '@mui/material/Stack';
import styles from '../../styles/Home.module.css'
import MatchupCard from './matchup'

export default function Schedules() {



  const props = {
    weekNumber: 12,
    matches: [{
      away: {
        name: "Buffalo Bills"
      },
      home: {
        name: "Detroit Lions"
      },
      notes: [{
        content: "Road Favorites cover",
        date: "11/22/22"
      }]
    },
    {
      away: {
        name: "New England Patriots"
      },
      home: {
        name: "Minnesota Vikings"
      },
      notes: [{
        content: "Cousins in primetime sucks. TNF unders hit",
        date: "11/19/22"
      }]
    }]
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Rosters</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Rosters
        </h1>
        
        <Stack direction="row" spacing={2}>
        {/* {
          props.matches.map((match, matchIndex) => {
            return (
              <MatchupCard {...match} key={matchIndex}></MatchupCard>
            )
          })
        } */}
        </Stack>
      </main>

    </div>
  )
}
